package com.example.someSpring.Controller;

import com.example.someSpring.Entity.User;
import com.example.someSpring.Repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.Map;

@Controller
public class GreetingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/")
    public String greeting(@RequestParam(name = "name", required = false, defaultValue = "World") String name, Map<String, Object> model) {
        model.put("name", name);
        return "greeting";
    }

    @GetMapping("/hello")
    public String hello(Map<String, Object> model) {
        Iterable<User> users = userRepository.findAll();
        model.put("users", users);
        return "hello";
    }
    /*
    @PostMapping("/hello")
    public String add(@RequestParam String name, Map<String, Object> model){
        User user = new User(name);
        userRepository.save(user);

        return hello(model);
    }

    @PostMapping("filter")
    public String filter(@RequestParam String filter, Map<String, Object> model){
        Iterable<User> byName;
        if(filter != null && !filter.isEmpty()) {
            byName = userRepository.findByName(filter);
        }
        else{
            byName = userRepository.findAll();
        }
        model.put("users", byName);

        return "hello";
    }

     */

}